name: Android Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release-aab:
    uses: Keshab1997/flutter-builder/.github/workflows/flutter-build.yml@v1.1.0
    with:
      flutter-channel: stable
      build-apk: false
      build-aab: true
      artifact-retention-days: 30
    secrets:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
