#!/usr/bin/env bash
# preview-hub.sh - keep <preview-dir>/index.html listing every branch preview.
#
# Why: the preview URL is only ever printed into an Actions run summary, and
# nobody opens those. One bookmarkable index page - …/<repo>/preview/ - that
# lists every branch is the difference between "the link is somewhere in
# Actions" and "the URL I always use". It is regenerated by every deploy, so it
# cannot go stale.
#
# What it touches: exactly one file, <preview-dir>/index.html on the Pages
# branch. Root files (a project's policy website, .nojekyll) and every other
# directory are left alone - that matters for repositories whose gh-pages root
# serves something of their own.
#
# Failure is never fatal: the calling workflow marks this step
# continue-on-error, because a missing index must not fail a deploy that
# already published a perfectly good preview.
#
# Usage:
#   bash scripts/preview-hub.sh --branch-dir preview/my-branch
#   bash scripts/preview-hub.sh --preview-dir preview --label my-branch
#
# Env: GITHUB_TOKEN (contents: write), GITHUB_REPOSITORY, PAGES_BRANCH
#      (default gh-pages), GITHUB_STEP_SUMMARY (optional).
set -euo pipefail

BRANCH_DIR="preview"
LABEL=""
PREVIEW_DIR=""

usage() {
  cat <<'HELP'
Keep the preview index page up to date.

  --branch-dir DIR    directory this run deployed, e.g. preview/my-branch
                      (the preview directory is its parent, the label its name)
  --preview-dir DIR   override the directory holding the per-branch previews
  --label NAME        override the branch label shown at the top
  -h, --help          this text

Env: GITHUB_TOKEN, GITHUB_REPOSITORY, PAGES_BRANCH (default gh-pages).
HELP
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --branch-dir)  BRANCH_DIR="${2:?--branch-dir needs a value}"; shift 2 ;;
    --preview-dir) PREVIEW_DIR="${2:?--preview-dir needs a value}"; shift 2 ;;
    --label)       LABEL="${2:?--label needs a value}"; shift 2 ;;
    -h|--help)     usage; exit 0 ;;
    *) printf 'preview-hub: unknown option: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

BRANCH_DIR="${BRANCH_DIR#/}"; BRANCH_DIR="${BRANCH_DIR%/}"
if [ -z "$PREVIEW_DIR" ]; then
  case "$BRANCH_DIR" in
    */*) PREVIEW_DIR="${BRANCH_DIR%/*}" ;;
    *)   PREVIEW_DIR="$BRANCH_DIR" ;;
  esac
fi
[ -n "$LABEL" ] || LABEL="${BRANCH_DIR##*/}"
PREVIEW_DIR="${PREVIEW_DIR#/}"; PREVIEW_DIR="${PREVIEW_DIR%/}"
[ -n "$PREVIEW_DIR" ] || { printf 'preview-hub: the preview directory is empty.\n' >&2; exit 2; }

: "${GITHUB_TOKEN:?preview-hub: GITHUB_TOKEN is required}"
: "${GITHUB_REPOSITORY:?preview-hub: GITHUB_REPOSITORY is required}"
command -v python3 >/dev/null 2>&1 || { printf 'preview-hub: python3 is required.\n' >&2; exit 2; }

python3 - "$PREVIEW_DIR" "$LABEL" <<'PY'
import base64
import html
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

preview_dir, label = sys.argv[1], sys.argv[2]
repo = os.environ["GITHUB_REPOSITORY"]
owner, _, name = repo.partition("/")
pages_branch = os.environ.get("PAGES_BRANCH", "gh-pages")
token = os.environ["GITHUB_TOKEN"]
api = f"https://api.github.com/repos/{repo}"
headers = {
    "Authorization": f"Bearer {token}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "preview-hub.sh",
}


def call(method: str, path: str, payload: dict | None = None):
    data = json.dumps(payload).encode() if payload is not None else None
    request = urllib.request.Request(
        api + path, data=data, method=method,
        headers={**headers, "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            raw = response.read().decode()
            return response.status, (json.loads(raw) if raw.strip() else {})
    except urllib.error.HTTPError as error:
        return error.code, {"message": error.read().decode(errors="replace")[:300]}


def listing() -> tuple[int, list]:
    status, data = call(
        "GET", f"/contents/{urllib.parse.quote(preview_dir)}?ref={pages_branch}")
    if status == 200 and isinstance(data, list):
        return status, data
    return status, []


status, items = listing()
branches = sorted({item["name"] for item in items if item.get("type") == "dir"})
if label not in branches:
    # The deploy that triggered this ran moments ago; if the API has not caught
    # up yet, the branch still belongs in its own index.
    branches.insert(0, label)
print(f"preview-hub: {len(branches)} branch preview(s): {', '.join(branches)}")

hub_url = f"https://{owner.lower()}.github.io/{name}/{preview_dir}/"
rows = "\n".join(
    f'      <li><a href="./{urllib.parse.quote(b)}/">{html.escape(b)}</a></li>'
    for b in branches)
page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(name)} - web previews</title>
</head>
<body style="margin:0;padding:2.5rem 1.25rem;background:#0f172a;color:#e2e8f0;
             font:16px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
  <main style="max-width:44rem;margin:0 auto">
    <h1 style="margin:0 0 .25rem;font-size:1.5rem">{html.escape(name)} - web previews</h1>
    <p style="margin:0 0 1.5rem;color:#94a3b8">
      One build per branch, updated whenever that branch is pushed.
      Latest: <strong>{html.escape(label)}</strong>.
    </p>
    <ul style="list-style:none;padding:0;margin:0;display:grid;gap:.5rem">
{rows}
    </ul>
    <p style="margin:1.5rem 0 0;color:#64748b;font-size:.875rem">
      Generated by <code>scripts/preview-hub.sh</code> from
      <a style="color:#93c5fd" href="https://github.com/{html.escape(repo)}">{html.escape(repo)}</a>.
    </p>
  </main>
</body>
</html>
"""

path = f"/contents/{urllib.parse.quote(f'{preview_dir}/index.html')}"
content = base64.b64encode(page.encode()).decode()
message = f"preview hub: {len(branches)} branch(es) ({label})"

for attempt in range(1, 6):
    status, existing = call("GET", f"{path}?ref={pages_branch}")
    sha = existing.get("sha") if status == 200 and isinstance(existing, dict) else None
    payload = {"message": message, "content": content, "branch": pages_branch}
    if sha:
        payload["sha"] = sha
    status, answer = call("PUT", path, payload)
    if status in (200, 201):
        print(f"preview-hub: updated {preview_dir}/index.html "
              f"({len(branches)} branch(es), attempt {attempt})")
        break
    # 409/422 mean somebody else wrote first (a deploy and a cleanup can land
    # together); re-reading the sha and trying again is the whole fix.
    print(f"preview-hub: attempt {attempt} got HTTP {status} "
          f"({str(answer.get('message', ''))[:120]}); retrying")
    time.sleep(min(2 * attempt, 8))
else:
    raise SystemExit("preview-hub: could not update the index after 5 attempts")

summary = os.environ.get("GITHUB_STEP_SUMMARY")
if summary:
    with open(summary, "a", encoding="utf-8") as handle:
        handle.write(f"\nAll previews of this repository: {hub_url}\n")
print(f"preview-hub: hub at {hub_url}")
PY
